const mongoose = require('mongoose');

const companySchema = new mongoose.Schema({
  name: { type: String, required: true },
  industry: {
    type: String,
    enum: [
      'Information Technology',
      'Finance',
      'Healthcare',
      'Education',
      'Retail',
      'Manufacturing',
      'Construction',
      'Telecommunications',
      'Transportation',
      'Agriculture',
      'Hospitality',
      'Real Estate',
      'Media',
      'Marketing',
      'Legal',
      'Government',
      'Energy',
      'Automotive',
      'Non-Profit',
      'Aerospace',
      'Food & Beverage',
      'Fashion',
      'Sports',
      'Environmental',
      'Human Resources',
    ],
    required: true,
  },
  description: String,
  logoUrl: String,
  website: String,
  location: String,
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  users: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
  createdAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model('Company', companySchema);
