export const industryOptions = [
  'Information Technology',
  'Finance',
  'Healthcare',
  'Education',
  'Retail',
  'Manufacturing',
  'Construction',
  'Telecommunications',
  'Transportation',
  'Agriculture',
  'Hospitality',
  'Real Estate',
  'Media',
  'Marketing',
  'Legal',
  'Government',
  'Energy',
  'Automotive',
  'Non-Profit',
  'Aerospace',
  'Food & Beverage',
  'Fashion',
  'Sports',
  'Environmental',
  'Human Resources',
];
